import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Kanit } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import './globals.css'
import NextAuthProvider from '@/context/NextAuthProvider'

const inter = Kanit({weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Service Hour Tracker',
  description: 'Generated by Sean Park',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider><ChakraProvider>
            {children}
        </ChakraProvider></NextAuthProvider>
      </body>
    </html>
  )
}
